#!/usr/bin/env bash
set -euo pipefail

BASE_DIR="${QA_DIR:-$HOME/Copilot-qa-history}"
MD_FILE="$BASE_DIR/CopilotHistorial.md"
JSON_DIR="$BASE_DIR/entries"
BACKUP_DIR="$BASE_DIR/backups"
BACKUP_KEEP="${BACKUP_KEEP:-50}"
BACKUP_ARCHIVE_DIR="$BACKUP_DIR/old_local"

usage(){
  cat <<EOF
Uso:
  copilot_log_qa.sh [-q "Pregunta"] [-a "Respuesta"] [-t "tag1,tag2"]
  copilot_log_qa.sh -Q pregunta.txt -A respuesta.txt
  copilot_log_qa.sh -e    # abrir editor para pregunta+respuesta
Opciones:
  -j    -> crear entries/<ID>.json
  -d DIR -> cambiar base dir
  -P     -> no hacer git push automático
EOF
  exit 1
}

EDITOR="${VISUAL:-${EDITOR:-vi}}"
MAKE_JSON=false
USE_EDITOR=false
NO_GIT_PUSH=false

while getopts ":q:a:t:Q:A:ejd:P" opt; do
  case $opt in
    q) Q="$OPTARG" ;;
    a) A="$OPTARG" ;;
    t) TAGS="$OPTARG" ;;
    Q) Q="$(cat "$OPTARG")" ;;
    A) A="$(cat "$OPTARG")" ;;
    e) USE_EDITOR=true ;;
    j) MAKE_JSON=true ;;
    d) BASE_DIR="$OPTARG"; MD_FILE="$BASE_DIR/CopilotHistorial.md"; JSON_DIR="$BASE_DIR/entries" ;;
    P) NO_GIT_PUSH=true ;;
    *) usage ;;
  esac
done

mkdir -p "$BASE_DIR" "$JSON_DIR"
mkdir -p "$BACKUP_DIR"

if [ "${USE_EDITOR:-false}" = true ]; then
  TMP="$(mktemp /tmp/qa.XXXXXX.md)"
  cat > "$TMP" <<'TEMPLATE'
# Edita entre las marcas. Borra comentarios cuando termines.
<<<QUESTION>>>
Escribe o pega aquí la pregunta (multi-línea).
<<<ENDQUESTION>>>
<<<ANSWER>>>
Escribe o pega aquí la respuesta (multi-línea).
<<<ENDANSWER>>>
Tags: tag1,tag2
TEMPLATE
  if [[ "${EDITOR}" == *" "* ]]; then
    eval "$EDITOR \"${TMP//\"/\\\"}\""
  else
    "$EDITOR" "$TMP"
  fi
  CONTENT="$(cat "$TMP")"
  rm -f "$TMP"
  Q="$(printf "%s\n" "$CONTENT" | awk '/^<<<QUESTION>>>/{p=1;next}/^<<<ENDQUESTION>>/{p=0}p')"
  A="$(printf "%s\n" "$CONTENT" | awk '/^<<<ANSWER>>>/{p=1;next}/^<<<ENDANSWER>>/{p=0}p')"
  TAGS="$(printf "%s\n" "$CONTENT" | awk -F'Tags:' '/Tags:/{print $2}' | sed 's/^[ \t]*//;s/[ \t]*$//')"
fi

if [ -z "${Q:-}" ] || [ -z "${A:-}" ]; then
  echo "Faltan pregunta o respuesta. Usa -q/-a, -Q/-A o -e."
  exit 1
fi

TIMESTAMP="$(date -u +"%Y%m%d_%H%M%S")"

# Repo and script commit hashes (short)
REPO_HASH="$(git -C "$BASE_DIR" rev-parse --short HEAD 2>/dev/null || echo 'nogit')"
SCRIPT_HASH="$(git -C "$BASE_DIR" log -n1 --pretty=format:%h -- copilot_log_qa_v2.sh 2>/dev/null || echo 'noscript')"

# SLUG: collapse newlines -> spaces, squeeze spaces, lowercase, transliterate, replace non-alnum with _
SLUG="$(printf "%s" "$Q" | tr '\r\n' ' ' | tr -s ' ' | sed 's/^ //;s/ $//' | tr '[:upper:]' '[:lower:]' \
  | iconv -f utf8 -t ascii//TRANSLIT 2>/dev/null | sed 's/[^a-z0-9 ]/_/g' | tr -s '_' | sed 's/^_//;s/_$//' | cut -c1-40)"
ID="${TIMESTAMP}_${SLUG:-entry}"

# make a repository-backed backup of the master MD file before modifying it
if [ -f "$MD_FILE" ]; then
  BACKUP_FILE="$BACKUP_DIR/CopilotHistorial.md.$TIMESTAMP"
  {
    printf '%s\n' '<!-- Backup generated by copilot_log_qa_v2.sh'
    printf '%s\n' "Timestamp: $TIMESTAMP"
    printf '%s\n' "RepoCommit: $REPO_HASH"
    printf '%s\n' "ScriptCommit: $SCRIPT_HASH"
    printf '%s\n' '-->'
    printf '%s\n' ''
    cat "$MD_FILE"
  } > "$BACKUP_FILE"

  # rotate backups: keep most recent $BACKUP_KEEP in repo, compress and move older ones to local archive
  mkdir -p "$BACKUP_ARCHIVE_DIR"
  # list backups sorted (oldest first)
  mapfile -t _bfiles < <(ls -1 "$BACKUP_DIR"/CopilotHistorial.md.* 2>/dev/null || true)
  if [ ${#_bfiles[@]} -gt 0 ]; then
    total=${#_bfiles[@]}
    move_count=$(( total - BACKUP_KEEP ))
    if [ "$move_count" -gt 0 ]; then
      # archive oldest files into per-month directories, then create/augment month tarballs
      declare -A months_seen
      for ((i=0;i<move_count;i++)); do
        src="${_bfiles[i]}"
        if [ ! -f "$src" ]; then
          continue
        fi
        month=$(date -r "$src" +%Y-%m)
        months_seen["$month"]=1
        mkdir -p "$BACKUP_ARCHIVE_DIR/$month"
        bname="$(basename "$src")"
        gzip -c "$src" > "$BACKUP_ARCHIVE_DIR/$month/${bname}.gz" || true
        rm -f "$src" || true
      done

      # for each month, merge into a single tar.gz (preserve prior contents)
      for month in "${!months_seen[@]}"; do
        month_dir="$BACKUP_ARCHIVE_DIR/$month"
        tarball="$BACKUP_ARCHIVE_DIR/${month}.tar.gz"
        tmpdir="$(mktemp -d)"
        # if tarball exists, extract it first to tmpdir to preserve prior entries
        if [ -f "$tarball" ]; then
          tar -xzf "$tarball" -C "$tmpdir" 2>/dev/null || true
        fi
        # copy current month files into tmpdir
        cp -a "$month_dir/"* "$tmpdir/" 2>/dev/null || true
        # recreate tarball from tmpdir
        tar -czf "$tarball" -C "$tmpdir" . || true
        rm -rf "$tmpdir"
        # remove the month dir after bundling
        rm -rf "$month_dir"
      done
    fi
  fi

  # ensure archive dir is ignored by git (use relative path)
  archive_rel="${BACKUP_ARCHIVE_DIR#$BASE_DIR/}"
  if [ -n "$archive_rel" ] && ! grep -Fxq "$archive_rel/" "$BASE_DIR/.gitignore" 2>/dev/null; then
    printf "%s/\n" "$archive_rel" >> "$BASE_DIR/.gitignore"
    git -C "$BASE_DIR" add .gitignore >/dev/null 2>&1 || true
    git -C "$BASE_DIR" commit -m "Ignore local backup archive" >/dev/null 2>&1 || true
  fi
fi

# compress remaining backups in BACKUP_DIR (those to be kept in the repo)
for f in "$BACKUP_DIR"/CopilotHistorial.md.*; do
  [ -e "$f" ] || continue
  # skip if it's already a tar.gz or inside old_local
  case "$f" in
    *old_local/*|*.tar.gz|*.gz) continue ;;
  esac
  gzip -c "$f" > "$f.gz" && rm -f "$f" || true
done

# Remove any leading '>' from lines of Q before adding blockquote
Q_CLEAN="$(printf "%s\n" "$Q" | sed 's/^[[:space:]]*>[[:space:]]*//')"
A_CLEAN="$A"
TAGS="$(printf "%s" "${TAGS:-}" | sed 's/^[ \t]*//;s/[ \t]*$//')"

ENTRY="$(cat <<EOF

## Entrada — $TIMESTAMP  (ID: $ID)
**RepoCommit:** $REPO_HASH
**ScriptCommit:** $SCRIPT_HASH
**Pregunta:**  
$(printf "%s\n" "$Q_CLEAN" | sed 's/^/> /g')

**Respuesta:**  
$(printf "%s\n" "$A_CLEAN" | sed 's/^/> /g')

**Contexto / Notas:**  

**Tags:** ${TAGS:-}

---
EOF
 )"

printf '%s' "$ENTRY" >> "$MD_FILE"

if [ "$MAKE_JSON" = true ]; then
  if command -v jq >/dev/null 2>&1; then
    jq -n --arg id "$ID" --arg t "$TIMESTAMP" --arg q "$Q" --arg a "$A" --arg tags "${TAGS:-}" \
      '{id:$id,timestamp:$t,question:$q,answer:$a,tags:$tags}' > "$JSON_DIR/$ID.json"
  else
    python3 - <<PY > "$JSON_DIR/$ID.json"
import json,sys
obj = {"id":"$ID","timestamp":"$TIMESTAMP","question":"""$Q""","answer":"""$A""","tags":"${TAGS:-}"}
print(json.dumps(obj, ensure_ascii=False))
PY
  fi
fi

if git -C "$BASE_DIR" rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  git -C "$BASE_DIR" add "$MD_FILE" >/dev/null 2>&1 || true
  git -C "$BASE_DIR" add "$JSON_DIR/$ID.json" >/dev/null 2>&1 || true
  # add the timestamped backup into the repo as well (if it exists)
  if [ -f "$BACKUP_DIR/CopilotHistorial.md.$TIMESTAMP" ]; then
    git -C "$BASE_DIR" add "$BACKUP_DIR/CopilotHistorial.md.$TIMESTAMP" >/dev/null 2>&1 || true
  fi
  git -C "$BASE_DIR" commit -m "Q&A: $ID" || true
  if [ "$NO_GIT_PUSH" = false ]; then
    git -C "$BASE_DIR" push || true
  fi
fi

echo "Entrada añadida: $MD_FILE (ID: $ID)"

